### ISSUE TITLE
DuckieTV 1.1.3 DEV uTorrent integration type error self.getRemote is not a function.

### ISSUE THREAD

**Issue by garfield69** [SchizoDuckie/DuckieTV#531]
Trying to connect DuckieTV 1.1.3 DEV with uTorrent 3.4.2 (38397).
Got a green dot, the ping was successful, and the session key was retrieved, but then we get a 
```javascript
TypeError: self.getRemote is not a function
```
at utorrent.js line 175.
![image](https://cloud.githubusercontent.com/assets/6933240/9241163/d4b58afe-41c3-11e5-8808-6f6bffb0a8fc.png)

**Comment by garfield69** [comment]
connecting DuckieTV 1.1.2 from Chrome store with uTorrent 3.4.2 (38397) succeeds.
![image](https://cloud.githubusercontent.com/assets/6933240/9241316/13a6fec6-41c6-11e5-9add-0c647fd9df81.png)

**Comment by garfield69** [comment]
introduced with 3adac8306669d83f2b33e0c06c2a16ee0c01b2f3.
But BaseTorrentClient.getRemote and uTorrent.getRemote don't appear to me to do the same thing
BaseTorrentClient.getRemote
```javascript
            getRemote: function() {
                if (this.remoteClass === null) {
                    throw "No torrent remote assigned to " + this.getName() + "implementation!";
                }
                return this.remoteClass;
            },
```
uTorrent.getRemote
```javascript
                getRemote: function() {
                    return uTorrentRemote;
                },
```
